GET http://localhost:4000/Usuarios

###


POST http://localhost:4000/Usuarios
Content-Type: application/json

{
  "nombre": "Juan",
  "contraseña": "134"
}

###

POST http://localhost:4000/Usuarios
Content-Type: application/json

{
  "nombre": "Juan",
  "contraseña": "124"
}

 